async function sendMessage(){if(state.busy)return;const input=$('#promptInput');const text=input.value.trim();if(!text&&!state.attachments.length)return;if(!state.ollamaOnline){showToast('Ollama no está conectado al bridge local.',true);return}state.busy=true;$('#sendBtn').disabled=true;const attachments=[...state.attachments];state.attachments=[];renderAttachments();input.value='';addMessage('user',text||'(Adjuntos)',{images:attachments.filter(a=>a.kind==='image').map(a=>a.dataUrl)});spendPoints(estimateCost());let model=state.selectedModel==='__auto__'?chooseAutoModel(text,attachments):state.selectedModel;if(!model){showToast('Instala al menos un modelo de Ollama.',true);state.busy=false;$('#sendBtn').disabled=false;return}const prompt=[$('#robloxMode').checked?($('#systemPrompt').value||DEFAULT_SYSTEM_PROMPT):'',...state.messages.slice(-12).map(m=>`${m.role}: ${m.content}`),...attachments.filter(a=>a.kind==='text').map(a=>`Archivo ${a.name}:\n${a.text}`),`user: ${text}`].filter(Boolean).join('\n\n');const images=attachments.filter(a=>a.kind==='image').map(a=>a.base64);try{const resp=await fetch(`${LOCAL_API_BASE}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,prompt,messages:[{role:'user',content:prompt,images}],options:{temperature:Number($('#temperature').value||.65)}})});if(!resp.ok)throw new Error((await resp.text())||`Error ${resp.status}`);let answer='';const type=resp.headers.get('content-type')||'';if(type.includes('application/json')){const data=await resp.json();answer=data.message?.content||data.response||data.content||JSON.stringify(data)}else{const reader=resp.body?.getReader();if(reader){const dec=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});for(const line of buf.split('\n')){if(!line.trim())continue;try{const d=JSON.parse(line);answer+=d.message?.content||d.response||''}catch{}}buf=''} }else answer=await resp.text()}if(!answer)answer='El modelo no devolvió texto.';addMessage('assistant',answer,{model})}catch(error){addMessage('assistant',`Error: ${error.message}`);showToast(error.message,true)}finally{state.busy=false;$('#sendBtn').disabled=false}}

async function connectCaptureSource(){if(state.capture.stream?.active)return true;if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Tu navegador no permite captura de pantalla.');const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const video=document.createElement('video');video.style.display='none';video.srcObject=stream;video.muted=true;video.playsInline=true;document.body.appendChild(video);await video.play();state.capture.stream=stream;state.capture.video=video;renderCaptureSourceStatus();stream.getVideoTracks()[0]?.addEventListener('ended',()=>stopCaptureSource(false),{once:true});return true}
function stopCaptureSource(notice=true){state.capture.stream?.getTracks().forEach(t=>t.stop());state.capture.video?.remove();state.capture.stream=null;state.capture.video=null;renderCaptureSourceStatus();if(notice)setCaptureProgress('Captura detenida.')}
function renderCaptureSourceStatus(){const b=$('#captureSourceBadge');if(!b)return;const on=!!state.capture.stream?.active;b.textContent=on?'● Ventana conectada':'Sin fuente';b.className=`capture-badge ${on?'online':'offline'}`;$('#connectCaptureSourceBtn')?.classList.toggle('hidden',on);$('#stopCaptureSourceBtn')?.classList.toggle('hidden',!on)}
function setCaptureProgress(t){const e=$('#captureProgress');if(e)e.textContent=t}
async function captureFrame(label='Vista actual'){await connectCaptureSource();const v=state.capture.video;if(!v?.videoWidth)await new Promise(r=>setTimeout(r,250));const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);const dataUrl=c.toDataURL('image/jpeg',.9);const shot={id:`cap_${Date.now()}`,label,dataUrl,base64:dataUrl.split(',')[1]||''};state.capture.shots.push(shot);state.attachments.push({kind:'image',name:`${label}.jpg`,dataUrl,base64:shot.base64,sourceCaptureId:shot.id});renderCaptureGallery();renderAttachments();updateCostEstimate();return shot}
function renderCaptureGallery(){const root=$('#captureGallery');if(!root)return;root.innerHTML=state.capture.shots.length?state.capture.shots.map(s=>`<div class="capture-shot"><img src="${s.dataUrl}"><div>${escapeHtml(s.label)}</div></div>`).join(''):'<div class="empty-state">Todavía no hay capturas.</div>'}
async function runSmartCapture({analyze=false}={}){try{setCaptureProgress('Capturando ventana real de Roblox Studio…');const s=await captureFrame('Vista actual');setCaptureProgress('Captura lista.');if(analyze){$('#promptInput').value='Analiza esta captura real de Roblox Studio. Señala problemas visuales y mejoras concretas sin inventar detalles.';switchView('chat');await sendMessage()}return s}catch(e){setCaptureProgress(e.message);showToast(e.message,true)}}
async function captureStudio(){return runSmartCapture({analyze:false})}
async function readStudioState(){try{const r=await directStudioTool('execute_luau',{code:'return "Place: "..game.Name.." | Workspace children: "..#workspace:GetChildren()',datamodel_type:'Edit'});showToast(r.text||r.result||'Estado leído')}catch(e){showToast(e.message,true)}}
$('#connectCaptureSourceBtn')?.addEventListener('click',()=>connectCaptureSource().catch(e=>showToast(e.message,true)));$('#stopCaptureSourceBtn')?.addEventListener('click',()=>stopCaptureSource(true));$('#smartCaptureBtn')?.addEventListener('click',()=>runSmartCapture({analyze:false}));$('#captureAnalyzeBtn')?.addEventListener('click',()=>runSmartCapture({analyze:true}));$('#clearCaptureGalleryBtn')?.addEventListener('click',()=>{state.capture.shots=[];renderCaptureGallery()});$('#studioCaptureBtn')?.addEventListener('click',captureStudio);$('#captureStudioBtn')?.addEventListener('click',captureStudio);$('#studioStateBtn')?.addEventListener('click',readStudioState);renderCaptureSourceStatus();renderCaptureGallery();init();
