function renderStudioTools(){const root=$('#studioToolList');if(!root)return;const f=($('#studioToolFilter')?.value||'').toLowerCase();const tools=(state.bridge.tools||[]).filter(t=>!f||String(t.name).toLowerCase().includes(f)||String(t.description||'').toLowerCase().includes(f));$('#studioToolCount').textContent=`${tools.length} comando${tools.length===1?'':'s'}`;root.innerHTML=tools.length?tools.map(t=>`<div class="studio-tool-card"><div class="model-name">${escapeHtml(t.name)}</div><p>${escapeHtml(t.description||'Sin descripción')}</p></div>`).join(''):'<div class="empty-state">No hay comandos disponibles.</div>'}
async function directStudioTool(name,args={}){const resolved=resolveToolName(name)||name;studioLog('run',resolved);const r=await bridgeRequest('call_tool',{name:resolved,arguments:args},30000);if(r.error)throw new Error(r.error);studioLog('ok',resolved);return r.result||r}
function renderSimpleMarkdown(text){return escapeHtml(String(text||'')).replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function addMessage(role,content,meta={}){const m={role,content,...meta,time:Date.now()};state.messages.push(m);renderMessage(m,state.messages.length-1);saveConversation();scrollChat();return m}
function renderMessage(m){const root=$('#messages');const el=document.createElement('div');el.className=`message ${m.role}`;el.innerHTML=`<div class="avatar">${m.role==='user'?'T':'M'}</div><div><div class="message-head"><strong>${m.role==='user'?'Tú':'MultiStudio'}</strong></div><div class="message-body">${renderSimpleMarkdown(m.content)}</div>${m.images?.length?`<div class="message-images">${m.images.map(x=>`<img src="${x}">`).join('')}</div>`:''}</div>`;root.appendChild(el);$('#welcome')?.classList.add('hidden')}
function scrollChat(){const s=$('#chatScroll');if(s)s.scrollTop=s.scrollHeight}
function saveConversation(){localStorage.setItem('ms_messages',JSON.stringify(state.messages.slice(-80)))}
function loadConversation(){try{state.messages=JSON.parse(localStorage.getItem('ms_messages')||'[]')}catch{state.messages=[]}for(const m of state.messages)renderMessage(m)}
function clearConversation(){state.messages=[];localStorage.removeItem('ms_messages');$('#messages').innerHTML='';$('#welcome')?.classList.remove('hidden')}
function estimateCost(){return 1500+state.attachments.length*1000}
function updateCostEstimate(){const el=$('#requestCost');if(el)el.textContent=`Costo estimado: ${formatNumber(estimateCost())} pts`}
async function fileToAttachment(file){if(file.type.startsWith('image/')){const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});return{kind:'image',name:file.name,dataUrl,base64:String(dataUrl).split(',')[1]||''}}const text=await file.text();return{kind:'text',name:file.name,text}}
function renderAttachments(){const root=$('#attachmentPreview');if(!root)return;root.classList.toggle('hidden',!state.attachments.length);root.innerHTML=state.attachments.map((a,i)=>`<div class="attachment-chip">${a.kind==='image'?`<img src="${a.dataUrl}">`:'📄'}<span>${escapeHtml(a.name)}</span><button data-att="${i}">×</button></div>`).join('');$$('[data-att]',root).forEach(b=>b.onclick=()=>{state.attachments.splice(Number(b.dataset.att),1);renderAttachments();updateCostEstimate()})}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${name}View`));$$('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
function loadSettings(){const p=localStorage.getItem('ms_system_prompt');$('#systemPrompt').value=p||DEFAULT_SYSTEM_PROMPT;const t=localStorage.getItem('ms_temperature');if(t)$('#temperature').value=t;$('#temperatureValue').textContent=$('#temperature').value}
function saveSettings(){localStorage.setItem('ms_system_prompt',$('#systemPrompt').value);localStorage.setItem('ms_temperature',$('#temperature').value)}
function bindEvents(){
$$('.nav-tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('#modelSelect').onchange=updateModelHint;$('#refreshModelsBtn').onclick=refreshStatus;$('#refreshModelsBtn2').onclick=refreshStatus;$('#refreshStudioBtn').onclick=refreshStudioStatus;$('#studioToolsBtn').onclick=()=>listStudioTools(true);$('#studioToolFilter').oninput=renderStudioTools;$('#clearStudioLogBtn').onclick=()=>{state.studioLog=[];renderStudioLog()};$('#newChatBtn').onclick=clearConversation;$('#attachBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{for(const f of e.target.files)state.attachments.push(await fileToAttachment(f));renderAttachments();updateCostEstimate();e.target.value=''};$('#promptInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});$('#sendBtn').onclick=sendMessage;$$('[data-prompt]').forEach(b=>b.onclick=()=>{$('#promptInput').value=b.dataset.prompt;sendMessage()});$('#temperature').oninput=()=>{$('#temperatureValue').textContent=$('#temperature').value;saveSettings()};$('#systemPrompt').onchange=saveSettings;$('#resetPointsBtn').onclick=()=>{state.points=MAX_POINTS;state.pointsUpdatedAt=Date.now();savePoints();renderPoints()};$('#clearAllBtn').onclick=()=>{if(confirm('¿Borrar conversaciones y ajustes?')){localStorage.clear();location.reload()}};$('#closeModalBtn').onclick=()=>$('#modalBackdrop').classList.add('hidden')}
async function init(){loadPoints();loadSettings();loadConversation();bindEvents();updateCostEstimate();renderStudioStatus();renderStudioTools();renderStudioLog();connectStudioBridge();setInterval(regenPoints,1000);await refreshStatus();setInterval(refreshStatus,30000);setInterval(refreshStudioStatus,8000)}
