/*
 * Reaction Forge v0.2 — Combinador universal de elementos para Sandboxels
 * Mezclas procedurales de dos elementos, reciclables para nuevas mezclas.
 * Editor visual de elementos y recetas, con guardado y exportación JSON.
 * Las mezclas simuladas son ficticias; no son fórmulas ni instrucciones químicas reales.
 * Licencia MIT. Proyecto comunitario no oficial.
 */
(function () {
    "use strict";
    if (window.ReactionForge) return;
    if (typeof elements === "undefined" || typeof behaviors === "undefined") {
        console.error("[Reaction Forge] No se encontró la API de Sandboxels.");
        return;
    }

    const VERSION = "0.2.0";
    const KEY = "reaction_forge_data_v1";
    const CAT = "reaction_forge";
    const OFFSETS = [[-1,0],[1,0],[0,-1],[0,1],[-1,-1],[-1,1],[1,-1],[1,1]];
    const VALID_ID = /^[a-z][a-z0-9_]{1,63}$/; // IDs generated by this mod only
    const hasElement = (id) => typeof id === "string" && id.length > 0 && id.length <= 240 &&
        Object.prototype.hasOwnProperty.call(elements, id) &&
        elements[id] && typeof elements[id] === "object";
    const empty = () => ({version:1, custom:[], recipes:[], generated:[]});
    const obj = (v) => v && typeof v === "object" && !Array.isArray(v);
    function readState() {
        try {
            const json = JSON.parse(localStorage.getItem(KEY) || "null");
            if (!obj(json)) return empty();
            return {
                version:1,
                custom:Array.isArray(json.custom) ? json.custom : [],
                recipes:Array.isArray(json.recipes) ? json.recipes : [],
                generated:Array.isArray(json.generated) ? json.generated : []
            };
        } catch (e) { console.warn("[Reaction Forge] Datos no legibles",e); return empty(); }
    }
    const state = readState();
    let saveTimer = null;
    let installed = false;
    let activeTab = "mix";
    const originalContact = new Map();
    const starterRules = new Map();
    const log = [];
    let restoring = false;
    let lateRestoreTimer = null;
    function physicalElement(id) {
        return hasElement(id) && id !== "unknown" &&
            elements[id].tool === undefined && elements[id].canPlace !== false;
    }
    function saveNow() {
        if (saveTimer !== null) clearTimeout(saveTimer);
        saveTimer = null;
        try { localStorage.setItem(KEY, JSON.stringify(state)); return true; }
        catch (e) { console.warn("[Reaction Forge] Guardado no disponible",e); status("Almacenamiento lleno o bloqueado. Exporta una copia JSON.",true); return false; }
    }
    function saveSoon() {
        // Do not postpone saving forever during a long reactor session.
        if (saveTimer === null) saveTimer = setTimeout(saveNow, 700);
    }
    if (typeof window.addEventListener === "function") {
        window.addEventListener("pagehide", () => { if (saveTimer !== null) { clearTimeout(saveTimer); saveNow(); } });
    }
    function status(msg,err) {
        const target=document.getElementById("rf-status");
        if (target) { target.textContent=msg; target.style.color=err ? "#ff9696" : "#a3e2c5"; }
    }
    function slug(name) {
        return String(name || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0,38);
    }
    function cap(value,lo,hi,fallback) {
        const v=Number(value);
        return Number.isFinite(v) ? Math.max(lo,Math.min(hi,v)) : fallback;
    }
    function validColor(value) { return /^#[0-9a-f]{6}$/i.test(value || ""); }
    function safeText(s,max=90) { return String(s || "").replace(/[<>]/g, "").slice(0,max); }
    function goodState(s) { return ["solid","liquid","gas"].includes(s) ? s : "solid"; }
    function makeElement(info) {
        const stateType=goodState(info.state);
        const behavior=stateType==="liquid" ? behaviors.LIQUID : (stateType==="gas" ? behaviors.GAS : behaviors.POWDER);
        return {
            name:safeText(info.name,75),
            color:validColor(info.color) ? info.color : "#b3b8df",
            behavior:info.fixed ? behaviors.WALL : behavior,
            category:CAT,
            state:stateType,
            density:cap(info.density,1,30000,1400),
            desc:"Reaction Forge — material ficticio. Puedes volver a mezclarlo en un reactor.",
            excludeRandom:true
        };
    }
    function putElement(id,def,live) {
        // Never overwrite vanilla elements or elements owned by another mod.
        if (hasElement(id)) throw new Error("ID de elemento ocupado: " + id);
        if (live && typeof addElement === "function" && document.getElementById("elementCountSpan")) {
            addElement(id,def);
        } else { elements[id]=def; }
    }
    const BASE = [
        ["rf_reactor",{name:"Reactor de mezclas", color:"#374b80",behavior:behaviors.WALL,category:CAT,state:"solid",density:4000,insulate:true,excludeRandom:true,desc:"Coloca al menos dos elementos vecinos. Transforma dos píxeles en uno nuevo cada cierto tiempo. No sustituye la química real.",tick:reactorTick}],
        ["rf_prism_solvent",{name:"Solvente prisma", color:"#70a7ff",state:"liquid",density:1060}],
        ["rf_crystal_dust",{name:"Polvo cristalino",color:"#ce8aff",state:"solid",density:2350}],
        ["rf_void_dust",{name:"Polvo del vacío",color:"#6654a7",state:"solid",density:1960}],
        ["rf_neon_vapor",{name:"Vapor neón",color:"#63f2b1",state:"gas",density:3}],
        ["rf_bio_gel",{name:"Gel biológico ficticio",color:"#6dcf75",state:"liquid",density:1220}],
        ["rf_prism_glass",{name:"Vidrio prisma",color:"#8ff7ef",state:"solid",density:2450,fixed:true}],
        ["rf_nebula_gel",{name:"Gel nebuloso",color:"#ab5bdb",state:"liquid",density:1300}],
        ["rf_star_crystal",{name:"Cristal estelar",color:"#fce17a",state:"solid",density:2800}],
        ["rf_fizz_vapor",{name:"Vapor efervescente",color:"#b0e8e8",state:"gas",density:4}],
        ["rf_living_crystal",{name:"Cristal vivo",color:"#71e2a1",state:"solid",density:2700}]
    ];
    for (const [id,def] of BASE) putElement(id,id==="rf_reactor"?def:makeElement(def),false);
    const starter = [
        ["water","rf_crystal_dust","rf_prism_glass"],
        ["rf_prism_solvent","rf_void_dust","rf_nebula_gel"],
        ["rf_nebula_gel","rf_neon_vapor","rf_star_crystal"],
        ["rf_crystal_dust","rf_bio_gel","rf_living_crystal"],
        ["rf_prism_solvent","rf_neon_vapor","rf_fizz_vapor"]
    ];
    // JSON avoids ambiguous combinations when other mods use punctuation in IDs.
    function pair(a,b) { return JSON.stringify([a,b].sort()); }
    function legacyPair(a,b) { return [a,b].sort().join("||"); }
    for (const [a,b,out] of starter) starterRules.set(pair(a,b),out);
    // All registered elements are eligible in the editor, including other mods,
    // one-letter IDs, special characters, tools and hidden elements. Only the
    // internal invalid-element placeholder is excluded. The reactor can consume
    // only physical pixels actually present in the world.
    function validInput(s) { return hasElement(s) && s !== "unknown"; }
    function validateCustom(x) {
        return obj(x) && typeof x.id==="string" && x.id.startsWith("rf_custom_") && VALID_ID.test(x.id) && typeof x.name==="string" && x.name.length<=75 && validColor(x.color) && ["solid","liquid","gas"].includes(x.state);
    }
    for (const x of state.custom.slice()) {
        if (!validateCustom(x) || hasElement(x.id)) continue;
        putElement(x.id,makeElement(x),false);
    }
    function hash32(s,seed) {
        let h=seed>>>0;
        for(let i=0;i<s.length;i++) { h ^= s.charCodeAt(i); h=Math.imul(h,16777619); }
        return (h>>>0).toString(16).padStart(8,"0");
    }
    function mixId(a,b) { const k=pair(a,b); return "rf_mix_"+hash32(k,2166136261)+hash32(k,374761393); }
    function legacyMixId(a,b) { const k=legacyPair(a,b); return "rf_mix_"+hash32(k,2166136261)+hash32(k,374761393); }
    function rgb(s) {
        if (obj(s) && Number.isFinite(s.r) && Number.isFinite(s.g) && Number.isFinite(s.b)) return [s.r,s.g,s.b];
        if (typeof s === "string" && /^#[0-9a-f]{3}$/i.test(s)) s="#"+s.slice(1).split("").map(c=>c+c).join("");
        if (validColor(s)) return [1,3,5].map(n=>parseInt(s.slice(n,n+2),16));
        const m=typeof s === "string" && s.match(/^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})/i);
        return m ? [Number(m[1]),Number(m[2]),Number(m[3])] : [153,153,153];
    }
    function hex(v) {return "#"+v.map(n=>Math.max(0,Math.min(255,Math.round(n))).toString(16).padStart(2,"0")).join("");}
    function elementColor(id) {
        const e=elements[id];
        const raw=Array.isArray(e.colorObject)?e.colorObject[0]:(e.colorObject|| (Array.isArray(e.color)?e.color[0]:e.color));
        return rgb(raw);
    }
    function mixColor(a,b) { const x=elementColor(a),y=elementColor(b);return hex(x.map((v,i)=>(v+y[i])/2)); }
    function mixPhase(a,b) {
        const sa=elements[a].state||"solid",sb=elements[b].state||"solid";
        if (sa==="gas"&&sb==="gas")return "gas";
        if (sa==="liquid"||sb==="liquid")return "liquid";
        return "solid";
    }
    function isValidGenerated(x) {
        return obj(x) && typeof x.a === "string" && typeof x.b === "string" &&
            typeof x.id === "string" && VALID_ID.test(x.id) &&
            x.id.startsWith("rf_mix_") && (mixId(x.a,x.b) === x.id || legacyMixId(x.a,x.b) === x.id) &&
            validColor(x.color) && typeof x.name === "string" && x.name.length <= 75 &&
            ["solid","liquid","gas"].includes(x.state);
    }
    function restoreGenerated(live=false) {
        // Dependency-based restoration: works for arbitrarily long chains and
        // for ingredients introduced by mods initialized after Reaction Forge.
        if (restoring) return 0;
        restoring = true;
        let pending=state.generated.filter(isValidGenerated);
        try {
            let progress=true;
            while (pending.length && progress) {
                progress=false;
                const next=[];
                for (const item of pending) {
                    if (hasElement(item.id)) continue;
                    if (!hasElement(item.a) || !hasElement(item.b)) { next.push(item); continue; }
                    putElement(item.id,makeElement(item),live);
                    progress=true;
                }
                pending=next;
            }
        } finally { restoring = false; }
        return pending.length;
    }
    const generatedIndex = new Map(state.generated.filter(isValidGenerated).map(item=>[item.id,item]));
    const generatedPairIndex = new Map(state.generated.filter(isValidGenerated).map(item=>[pair(item.a,item.b),item]));
    function makeGenerated(a,b) {
        const key=pair(a,b);
        const previous=generatedPairIndex.get(key);
        if (previous) {
            const id=previous.id;
            if (!hasElement(id)) putElement(id,makeElement(previous),installed);
            else if (elements[id].category!==CAT) throw new Error("Otra modificación utiliza este identificador. No se ha sobrescrito.");
            return id;
        }
        const id=mixId(a,b);
        // Extremely uncommon hash collisions must not destroy existing materials.
        if (hasElement(id) || generatedIndex.has(id))
            throw new Error("Colisión de identificador. No se modificó el elemento existente.");
        const ea=elements[a],eb=elements[b];
        const data={id,a,b,name:safeText(`${ea.name||a} + ${eb.name||b}`,75),color:mixColor(a,b),state:mixPhase(a,b),density:Math.round((cap(ea.density,1,30000,1000)+cap(eb.density,1,30000,1000))/2)};
        putElement(id,makeElement(data),installed);
        state.generated.push(data);
        generatedIndex.set(id,data);
        generatedPairIndex.set(key,data);
        saveSoon();
        if(state.generated.length===1500) status("Ya hay 1500 mezclas guardadas: exporta tu biblioteca para evitar pérdidas.",true);
        return id;
    }
    restoreGenerated(false);
    function recipeRecord(x) {
        return obj(x) && typeof x.a === "string" && x.a.length <= 240 &&
            typeof x.b === "string" && x.b.length <= 240 &&
            typeof x.out === "string" && x.out.length <= 240 && typeof x.contact === "boolean";
    }
    function goodRecipe(x) {
        return recipeRecord(x) && validInput(x.a) && validInput(x.b) && physicalElement(x.out);
    }
    function resolveRecipe(a,b) {
        const k=pair(a,b);
        for(let i=state.recipes.length-1;i>=0;i--) {
            const r=state.recipes[i];
            if (recipeRecord(r) && pair(r.a,r.b)===k && physicalElement(r.out)) return r.out;
        }
        const starter=starterRules.get(k);
        return starter && physicalElement(starter) ? starter : null;
    }
    function blend(a,b) {
        // Reload mix chains that depended on mods that were initialized later.
        if (!validInput(a)||!validInput(b)) restoreGenerated(installed);
        if (!validInput(a)||!validInput(b)) throw new Error("Elemento no encontrado. Usa un ID de Sandboxels o de un mod instalado.");
        const out=resolveRecipe(a,b)||makeGenerated(a,b);
        log.unshift({a,b,out});
        if(log.length>40) log.length=40;
        return out;
    }
    function blendMany(list) {
        if (!Array.isArray(list) || list.length < 2 || list.length > 32)
            throw new Error("Escribe entre 2 y 32 elementos separados por comas o saltos de línea.");
        if (!list.every(validInput)) {
            restoreGenerated(installed);
            if (!list.every(validInput)) throw new Error("Un ingrediente no existe en Sandboxels. Revisa los IDs.");
        }
        let result=list[0];
        for(let i=1;i<list.length;i++) result=blend(result,list[i]);
        return result;
    }
    function reactorTick(pixel) {
        if ((pixelTicks + pixel.x*3 + pixel.y) % 12 !== 0) return;
        const near=[];
        for(const [dx,dy] of OFFSETS) {
            const x=pixel.x+dx,y=pixel.y+dy;
            if (outOfBounds(x,y)) continue;
            const n=pixelMap[x]?.[y];
            if (n && !n.del && n.element!=="rf_reactor" && physicalElement(n.element)) near.push(n);
        }
        if(near.length<2) return;
        let a=null,b=null;
        // Give priority to explicit recipes when the reactor has many neighbors.
        for(let i=0;i<near.length-1 && !a;i++)for(let j=i+1;j<near.length;j++) {
            if(near[i].element!==near[j].element && resolveRecipe(near[i].element,near[j].element)) {a=near[i];b=near[j];break;}
        }
        if(!a) {a=near[0]; b=near[1];}
        if(!b) return;
        let out;
        try {out=blend(a.element,b.element);} catch(e){return;}
        // Consume only the two ingredient pixels, keeping the reactor in place.
        if(pixelMap[a.x]?.[a.y]!==a || pixelMap[b.x]?.[b.y]!==b) return;
        changePixel(a,out);
        deletePixel(b.x,b.y);
        if(log.length%8===0) refreshIfOpen();
    }
    // Native contact reactions are opt-in and preserve native rules by refusing collisions.
    function setContact(x) {
        if(!x.contact) return {ok:true};
        if (!goodRecipe(x) || !physicalElement(x.a) || !physicalElement(x.b))
            return {ok:false,message:"Los contactos requieren ingredientes y productos que puedan existir como píxeles. La receta del laboratorio se conserva."};
        for(const [a,b] of [[x.a,x.b],[x.b,x.a]]) {
            if (elements[a].reactions && elements[a].reactions[b] !== undefined && !originalContact.has(JSON.stringify([a,b]))) return {ok:false,message:`${a} y ${b} ya tienen una reacción nativa; usa el reactor.`};
        }
        for(const [a,b] of [[x.a,x.b],[x.b,x.a]]) {
            if(!elements[a].reactions) elements[a].reactions={};
            const k=JSON.stringify([a,b]);
            if(!originalContact.has(k)) originalContact.set(k,{prev:elements[a].reactions[b],target:elements[a].reactions});
            elements[a].reactions[b]={elem1:x.out,elem2:null,chance:1};
        }
        return {ok:true};
    }
    function unsetContact(x) {
        for(const [a,b] of [[x.a,x.b],[x.b,x.a]]) {
            const k=JSON.stringify([a,b]),p=originalContact.get(k);
            if(!p||!elements[a]?.reactions) continue;
            const current=elements[a].reactions[b];
            if(current && current.elem1===x.out && current.elem2===null) {
                if(p.prev===undefined) delete elements[a].reactions[b];
                else elements[a].reactions[b]=p.prev;
            }
            originalContact.delete(k);
        }
    }
    function addCustom(name,color,phase,density) {
        const base=slug(name);
        if(base.length<1) throw new Error("Escribe un nombre válido para el material.");
        const id="rf_custom_"+base;
        if(elements[id]) throw new Error("Ya existe un material con ese nombre.");
        const data={id,name:safeText(name,75),color,state:goodState(phase),density:cap(density,1,30000,1500)};
        if(!validColor(data.color))throw new Error("El color no es válido.");
        putElement(id,makeElement(data),installed);
        state.custom.push(data);
        saveNow();
        return id;
    }
    function addRecipe(a,b,out,contact) {
        if(!validInput(a)||!validInput(b)) throw new Error("Introduce dos IDs que existan en Sandboxels, incluidos mods y herramientas.");
        if(!physicalElement(out)) throw new Error("El producto de la receta debe ser un píxel colocable; las herramientas sí pueden ser ingredientes virtuales.");
        const entry={a,b,out,contact:!!contact};
        const prev=state.recipes.find(r=>pair(r.a,r.b)===pair(a,b));
        if(prev)unsetContact(prev);
        const applied=setContact(entry);
        if(!applied.ok) entry.contact=false;
        if(prev)state.recipes.splice(state.recipes.indexOf(prev),1);
        state.recipes.push(entry);
        saveNow();
        return applied;
    }
    function restoreContacts() {
        for (const x of state.recipes) {
            if(!recipeRecord(x) || !x.contact || !goodRecipe(x)) continue;
            const r=setContact(x);
            if(!r.ok) { x.contact=false; saveSoon(); }
        }
    }
    function scheduleRestore() {
        if(lateRestoreTimer!==null)return;
        lateRestoreTimer=setTimeout(()=>{
            lateRestoreTimer=null;
            restoreGenerated(installed);
            restoreContacts();
        },0);
    }
    function removeRecipe(k) {
        const i=state.recipes.findIndex(x=>pair(x.a,x.b)===k);
        if(i<0)return;
        const x=state.recipes[i];unsetContact(x);state.recipes.splice(i,1);saveNow();renderTab();
    }
    // Use DOM methods and textContent for all user-provided strings: no user HTML injection.
    function dom(tag,attrs={},value) {
        const n=document.createElement(tag);
        for(const [k,v] of Object.entries(attrs)) {
            if(k==="class") n.className=v;
            else if(k==="type" || k==="placeholder" || k==="title" || k==="min" || k==="max" || k==="step" || k==="accept" || k==="list" || k==="id") n.setAttribute(k,v);
        }
        if(value!==undefined)n.textContent=value;
        return n;
    }
    function field(label,placeholder,initial="",type="text") {
        const wrap=dom("label",{class:"rf-field"});wrap.appendChild(dom("span",{},label));
        const el=dom("input",{type,placeholder});el.value=initial;wrap.appendChild(el);
        return {wrap,el};
    }
    function select(label,options,initial) {
        const wrap=dom("label",{class:"rf-field"});wrap.appendChild(dom("span",{},label));const el=dom("select");
        for(const [val,title] of options){const opt=dom("option",{},title);opt.value=val;el.appendChild(opt);}
        el.value=initial||options[0][0];wrap.appendChild(el);return {wrap,el};
    }
    function btn(label,handler,kind="") {
        const b=dom("button",{class:"rf-action "+kind,type:"button"},label);b.addEventListener("click",handler);return b;
    }
    function message(e){status(e?.message||String(e),true);}
    function openPanel(){restoreGenerated(installed);document.getElementById("rf-root")?.classList.remove("rf-hide");renderTab();}
    function closePanel(){document.getElementById("rf-root")?.classList.add("rf-hide");}
    function refreshIfOpen(){const root=document.getElementById("rf-root");if(root && !root.classList.contains("rf-hide") && activeTab==="history")renderTab();}
    function listRow(title,desc,act) {
        const row=dom("div",{class:"rf-row"}),txt=dom("div",{class:"rf-row-text"});txt.appendChild(dom("strong",{},title));txt.appendChild(dom("small",{},desc));row.appendChild(txt);
        if(act)row.appendChild(act);return row;
    }
    function inputNames(container) {
        const datalist=dom("datalist",{id:"rf-elements"});
        for(const id of Object.keys(elements).filter(validInput).sort()) {
            const op=dom("option");op.value=id;
            op.label=safeText(elements[id].name || id,75);
            datalist.appendChild(op);
        }
        container.appendChild(datalist);
    }
    function renderTab() {
        const wrap=document.getElementById("rf-body");if(!wrap)return;
        wrap.replaceChildren();
        for(const el of document.querySelectorAll("[data-rf-tab]"))el.classList.toggle("rf-active",el.dataset.rfTab===activeTab);
        if(activeTab==="mix") {
            const total=Object.keys(elements).filter(validInput).length;
            wrap.appendChild(dom("p",{class:"rf-lead"},`Todos los elementos registrados: ${total}. Se incluyen elementos originales, de otros mods, herramientas y tus Customs. Combina dos iguales o diferentes; puedes volver a combinar los resultados.`));
            const a=field("Elemento A (identificador)","water","water"), b=field("Elemento B (identificador)","rf_crystal_dust","rf_crystal_dust");
            a.el.setAttribute("list","rf-elements");b.el.setAttribute("list","rf-elements");wrap.append(a.wrap,b.wrap);
            inputNames(wrap);
            wrap.appendChild(btn("Crear combinación y seleccionar",()=>{try{const out=blend(a.el.value.trim(),b.el.value.trim());if(typeof selectElement==="function")selectElement(out);if(typeof selectCategory==="function")selectCategory(CAT);status(`Resultado: ${elements[out].name||out} (${out})`);renderTab();}catch(e){message(e);}},"rf-primary"));
            const many=field("Combinar varios (2 a 32 IDs separados por comas o líneas)","water, sand, fire");
            const broad=dom("textarea",{placeholder:"water, sand, fire"});broad.rows=3;
            many.el.replaceWith(broad);
            wrap.appendChild(many.wrap);
            wrap.appendChild(btn("Crear mezcla múltiple",()=>{try{
                const list=broad.value.split(/[,\n]+/).map(s=>s.trim()).filter(Boolean);
                const out=blendMany(list);
                if(typeof selectElement==="function")selectElement(out);
                if(typeof selectCategory==="function")selectCategory(CAT);
                status(`Mezcla de ${list.length} elementos: ${out}`);renderTab();
            }catch(e){message(e);}},"rf-primary"));
            wrap.appendChild(btn("Actualizar catálogo de elementos",()=>{restoreGenerated(installed);renderTab();}));
            wrap.appendChild(dom("p",{class:"rf-info"},"Todos los IDs disponibles sirven para mezclas de laboratorio, incluso los de herramientas y otros mods. En el mundo, el Reactor solo usa píxeles físicos y no consume otros reactores. La química original del juego se conserva."));
            const samples=dom("div",{class:"rf-samples"});samples.appendChild(dom("strong",{},"Prueba estas combinaciones:"));
            for(const [aa,bb,oo] of starter) samples.appendChild(btn(`${aa} + ${bb} → ${oo}`,()=>{a.el.value=aa;b.el.value=bb;status("Receta de ejemplo cargada. Pulsa Crear combinación.");}));
            wrap.appendChild(samples);
        }
        if(activeTab==="custom") {
            wrap.appendChild(dom("p",{class:"rf-lead"},"Crea una sustancia custom. Luego úsala en el reactor o como ingrediente de nuevas recetas."));
            const n=field("Nombre del nuevo material","Cristal arcoíris"),c=field("Color hexadecimal","#ff72a1","#ff72a1","color"),d=field("Densidad (1-30000)","1400","1400","number");
            d.el.min="1";d.el.max="30000";
            const ph=select("Estado físico",[["solid","Sólido / polvo"],["liquid","Líquido"],["gas","Gas"]],"solid");
            wrap.append(n.wrap,c.wrap,ph.wrap,d.wrap);
            wrap.appendChild(btn("Crear material custom",()=>{try{const id=addCustom(n.el.value,c.el.value,ph.el.value,d.el.value);status(`Creado ${id}. Aparece en Reaction Forge.`);renderTab();}catch(e){message(e);}},"rf-primary"));
            wrap.appendChild(dom("h4",{},`Mis materiales (${state.custom.filter(x=>elements[x.id]).length})`));
            for(const item of state.custom.filter(x=>elements[x.id]))wrap.appendChild(listRow(item.name,`${item.id} · ${item.state} · ${item.color}`,btn("Seleccionar",()=>{selectElement(item.id);selectCategory(CAT);closePanel();})));
        }
        if(activeTab==="recipes") {
            wrap.appendChild(dom("p",{class:"rf-lead"},"Diseña reacciones exactas A + B → producto. El reactor siempre las respeta. También puedes activar reacciones por contacto cuando no choquen con las nativas."));
            const a=field("Ingrediente A","water"),b=field("Ingrediente B","rf_void_dust"),out=field("Resultado (debe existir)","rf_nebula_gel");
            for(const f of [a,b,out]){f.el.setAttribute("list","rf-elements");wrap.appendChild(f.wrap);}inputNames(wrap);
            const label=dom("label",{class:"rf-check"});const checkbox=dom("input",{type:"checkbox"});label.append(checkbox,dom("span",{},"Reaccionar también al tocarse (sin reemplazar reacciones nativas)"));wrap.appendChild(label);
            wrap.appendChild(btn("Guardar receta",()=>{try{const r=addRecipe(a.el.value.trim(),b.el.value.trim(),out.el.value.trim(),checkbox.checked);status(r.ok?"Receta guardada.":`Guardada solo para reactor: ${r.message}`);renderTab();}catch(e){message(e);}},"rf-primary"));
            wrap.appendChild(dom("h4",{},`Mis recetas (${state.recipes.length})`));
            for(const r of state.recipes){if(!goodRecipe(r))continue;wrap.appendChild(listRow(`${r.a} + ${r.b} → ${r.out}`,r.contact?"Reactor + contacto":"Solo reactor",btn("Eliminar",()=>removeRecipe(pair(r.a,r.b)))));}
        }
        if(activeTab==="history") {
            wrap.appendChild(dom("p",{class:"rf-lead"},`Combinaciones generadas: ${state.generated.filter(x=>elements[x.id]).length}. No hay una lista fija de recetas: puedes seguir combinando productos con productos. El espacio y la memoria del navegador son finitos.`));
            wrap.appendChild(btn("Exportar todo a JSON",exportData,"rf-primary"));
            const file=dom("input",{type:"file",accept:".json,application/json"});
            file.addEventListener("change",async()=>{try{const content=await file.files[0]?.text();if(!content)return;importData(content);status("Importado. Recarga Sandboxels para recuperar todos los elementos.");renderTab();}catch(e){message(e);}});wrap.appendChild(file);
            wrap.appendChild(dom("h4",{},"Últimas combinaciones de esta sesión"));
            for(const r of log.slice(0,25))wrap.appendChild(listRow(`${r.a} + ${r.b}`,`→ ${r.out}`,elements[r.out]?btn("Elegir",()=>{selectElement(r.out);selectCategory(CAT);closePanel();}):null));
            wrap.appendChild(dom("h4",{},"Resultados guardados (últimos 70)"));
            for(const r of state.generated.slice(-70).reverse()) if(elements[r.id]) wrap.appendChild(listRow(r.name,`${r.id} · ${r.state}`,btn("Elegir",()=>{selectElement(r.id);selectCategory(CAT);closePanel();})));
            wrap.appendChild(dom("p",{class:"rf-info"},"Exportar hace una copia de seguridad. Si borras los datos del sitio, también borrarás la biblioteca local. No importes archivos JSON desconocidos."));
        }
    }
    function exportData(){
        saveNow();const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const u=URL.createObjectURL(blob);const a=dom("a");a.href=u;a.download="reaction_forge_backup.json";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);status("Copia JSON exportada.");
    }
    function importData(raw){
        if(raw.length>2500000)throw new Error("El archivo es demasiado grande (máx. 2,5 MB).");
        const d=JSON.parse(raw);
        if(!obj(d)||d.version!==1||!Array.isArray(d.custom)||!Array.isArray(d.recipes)||!Array.isArray(d.generated))throw new Error("Formato JSON no compatible.");
        let customs=0,recipes=0,generations=0;
        for(const x of d.custom){if(!validateCustom(x)||state.custom.some(v=>v.id===x.id)||elements[x.id])continue;
            state.custom.push({id:x.id,name:safeText(x.name,75),color:x.color,state:x.state,density:cap(x.density,1,30000,1400)});
            putElement(x.id,makeElement(x),installed);customs++;
        }
        for(const x of d.generated){
            if(!isValidGenerated(x) || generatedIndex.has(x.id) || generatedPairIndex.has(pair(x.a,x.b)) || hasElement(x.id))continue;
            const clean={id:x.id,a:x.a,b:x.b,name:safeText(x.name,75),color:x.color,state:goodState(x.state),density:cap(x.density,1,30000,1400)};
            state.generated.push(clean);generatedIndex.set(clean.id,clean);
            generatedPairIndex.set(pair(clean.a,clean.b),clean);generations++;
        }
        // Resolves dependent materials even when JSON lists them in reverse order.
        restoreGenerated(installed);
        for(const x of d.recipes){if(!recipeRecord(x))continue;
            if(!goodRecipe(x)) {
                // Keep references to elements from optional mods not loaded yet.
                if(!state.recipes.some(v=>recipeRecord(v) && pair(v.a,v.b)===pair(x.a,x.b))) {
                    state.recipes.push({a:x.a,b:x.b,out:x.out,contact:x.contact});recipes++;
                }
            } else { addRecipe(x.a,x.b,x.out,x.contact); recipes++; }
        }
        restoreContacts();
        saveNow();status(`Importados: ${customs} materiales, ${generations} mezclas y ${recipes} recetas.`);
    }
    function installUI() {
        if(installed || document.getElementById("rf-root"))return;
        restoreGenerated(true);
        installed=true;
        const st=dom("style");st.textContent=`
#rf-root{position:fixed;inset:0;background:#060b16bf;z-index:999999;display:flex;justify-content:center;align-items:center;padding:10px;box-sizing:border-box;font:14px/1.45 system-ui,Arial,sans-serif;color:#eaf1ff}
#rf-root.rf-hide{display:none}#rf-root *{box-sizing:border-box}
#rf-panel{width:min(700px,100%);max-height:min(89vh,870px);display:flex;flex-direction:column;background:#151e32;border:1px solid #5167a1;border-radius:14px;box-shadow:0 20px 65px #000a;overflow:hidden}
#rf-panel button,#rf-panel input,#rf-panel select,#rf-panel textarea{font:inherit}#rf-panel button{cursor:pointer}#rf-header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 17px;background:#222d47}
#rf-header h2{font-size:18px;margin:0}#rf-header small{font-size:11px;color:#b8c8e6}#rf-tabs{display:flex;overflow-x:auto;gap:5px;padding:8px;background:#12192b}
#rf-tabs button{background:#2a3450;color:#fff;border:1px solid #435275;border-radius:7px;padding:8px 11px;white-space:nowrap}#rf-tabs button.rf-active{background:#367bc0}
#rf-body{padding:16px 18px;overflow:auto;min-height:100px;flex:1}#rf-body h4{font-size:14px;margin:20px 0 9px}
#rf-body .rf-lead{margin:0 0 14px;color:#d4e1ff}#rf-body .rf-info{background:#26334f;padding:9px;border-radius:7px;color:#e0e9ff}
#rf-body .rf-field{display:flex;flex-direction:column;gap:5px;margin:9px 0}#rf-body .rf-field span{font-size:12px;color:#cedfff}
#rf-body input:not([type=checkbox]),#rf-body select,#rf-body textarea{width:100%;min-height:36px;background:#0c1423;color:#fff;border:1px solid #60739a;border-radius:7px;padding:7px}
#rf-body .rf-action,#rf-header .rf-action{color:#fff;border:1px solid #6178a0;background:#334566;border-radius:7px;padding:7px 11px;margin:3px}
#rf-body .rf-primary{background:#245ea0;border-color:#529bdc;font-weight:700;padding:10px 13px}
#rf-body .rf-row{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #344361;padding:8px 0;gap:5px;min-width:0}
#rf-body .rf-row-text{min-width:0;overflow-wrap:anywhere}#rf-body .rf-row strong{font-size:12px;display:block}#rf-body .rf-row small{font-size:11px;color:#a9bddf;display:block}
#rf-body .rf-check{display:flex;align-items:center;gap:10px;padding:9px 0}#rf-body .rf-samples{margin-top:16px}#rf-body .rf-samples strong{display:block;margin-bottom:8px}
#rf-status{min-height:34px;padding:9px 16px;color:#a3e2c5;background:#111b2c;border-top:1px solid #344361;font-size:12px;overflow-wrap:anywhere}
@media(max-width:540px){#rf-panel{max-height:92vh}#rf-body{padding:11px}#rf-header{padding:10px}#rf-tabs button{font-size:12px;padding:7px}#rf-header h2{font-size:15px}}
`;document.head.appendChild(st);
        const root=dom("div",{id:"rf-root",class:"rf-hide"}),panel=dom("section",{id:"rf-panel"}),header=dom("div",{id:"rf-header"});
        const title=dom("div");title.append(dom("h2",{},"⚗️ Reaction Forge"),dom("small",{},"v"+VERSION+" · química creativa · Sandboxels"));
        header.append(title,btn("Cerrar ✕",closePanel));panel.appendChild(header);
        const tabs=dom("div",{id:"rf-tabs"});for(const [id,label] of [["mix","Combinar"],["custom","Customs"],["recipes","Recetas"],["history","Mis mezclas"]]) {
            const button=btn(label,()=>{activeTab=id;renderTab();});button.dataset.rfTab=id;tabs.appendChild(button);
        }panel.appendChild(tabs);panel.appendChild(dom("div",{id:"rf-body"}));panel.appendChild(dom("div",{id:"rf-status"},"Listo para experimentar con mezclas ficticias."));root.appendChild(panel);
        root.addEventListener("click",(e)=>{if(e.target===root)closePanel();});
        document.addEventListener("keydown",(e)=>{if(e.key==="Escape"&&!root.classList.contains("rf-hide"))closePanel();});
        document.body.appendChild(root);
        const launch=dom("button",{type:"button",id:"rf-launch"},"⚗️ Reaction Forge");
        launch.className="controlButton";launch.title="Abrir laboratorio de mezclas y reacciones";launch.addEventListener("click",openPanel);
        const near=document.getElementById("modStudioButton")||document.getElementById("modsButton");
        if(near)near.insertAdjacentElement("afterend",launch);
        else document.body.appendChild(launch);
        restoreContacts();
        // Third-party elements created live are picked up without restarting.
        if(typeof onAddElement === "function") onAddElement(()=>{if(!restoring)scheduleRestore();});
        renderTab();
    }
    window.ReactionForge=Object.freeze({version:VERSION,blend,blendMany,addCustom,addRecipe,
        elementIds:()=>Object.keys(elements).filter(validInput),
        restore:()=>restoreGenerated(installed),importJSON:importData,
        getData:()=>JSON.parse(JSON.stringify(state)),open:openPanel});
    const queueInstall=()=>setTimeout(installUI,0);
    if(typeof runAfterLoad==="function")runAfterLoad(queueInstall);
    else if(document.readyState==="complete")queueInstall();
    else window.addEventListener("load",queueInstall,{once:true});
})();