from pathlib import Path
import sys

root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('buildsrc/MultiAI_Android')

gradle = root / 'app/build.gradle'
s = gradle.read_text()
s = s.replace('versionCode 5', 'versionCode 6').replace("versionName '0.5.0-alpha'", "versionName '0.5.1-alpha'")
if 'play-services-auth' not in s:
    s = s.replace("implementation 'com.google.android.material:material:1.12.0'", "implementation 'com.google.android.material:material:1.12.0'\n    implementation 'com.google.android.gms:play-services-auth:21.2.0'")
gradle.write_text(s)

kt = root / 'app/src/main/java/com/multiai/assistant/MainActivity.kt'
s = kt.read_text()
if 'GoogleSignInClient' not in s:
    s = s.replace('import android.webkit.WebViewClient\nimport android.widget.Toast\n', 'import android.webkit.WebViewClient\nimport android.widget.Toast\nimport com.google.android.gms.auth.api.signin.GoogleSignIn\nimport com.google.android.gms.auth.api.signin.GoogleSignInClient\nimport com.google.android.gms.auth.api.signin.GoogleSignInOptions\nimport com.google.android.gms.common.api.ApiException\n')
    s = s.replace('import java.security.KeyStore\n', 'import java.security.KeyStore\nimport java.security.MessageDigest\n')
    s = s.replace('    private var tts: TextToSpeech? = null\n', '    private var tts: TextToSpeech? = null\n    private lateinit var googleSignInClient: GoogleSignInClient\n')
    s = s.replace('        private const val SPEECH_REQUEST = 2002\n', '        private const val SPEECH_REQUEST = 2002\n        private const val GOOGLE_SIGN_IN_REQUEST = 2003\n')
    s = s.replace('        tts = TextToSpeech(this, this)\n        webView = findViewById(R.id.webView)\n', '''        tts = TextToSpeech(this, this)\n        val googleOptions = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)\n            .requestEmail()\n            .build()\n        googleSignInClient = GoogleSignIn.getClient(this, googleOptions)\n        webView = findViewById(R.id.webView)\n''')
    s = s.replace('''        } else if (requestCode == SPEECH_REQUEST && resultCode == Activity.RESULT_OK) {\n            val text = data?.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS)?.firstOrNull().orEmpty()\n            callback("window.NativeBridgeCallbacks.onVoiceResult", JSONObject.quote(text))\n        }\n''', '''        } else if (requestCode == SPEECH_REQUEST && resultCode == Activity.RESULT_OK) {\n            val text = data?.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS)?.firstOrNull().orEmpty()\n            callback("window.NativeBridgeCallbacks.onVoiceResult", JSONObject.quote(text))\n        } else if (requestCode == GOOGLE_SIGN_IN_REQUEST) {\n            try {\n                val account = GoogleSignIn.getSignedInAccountFromIntent(data).getResult(ApiException::class.java)\n                val obj = JSONObject()\n                    .put("ok", true)\n                    .put("id", account.id ?: "")\n                    .put("name", account.displayName ?: account.givenName ?: "Usuario")\n                    .put("email", account.email ?: "")\n                    .put("photo", account.photoUrl?.toString() ?: "")\n                callback("window.NativeBridgeCallbacks.onGoogleSignIn", obj.toString())\n            } catch (e: Exception) {\n                val obj = JSONObject().put("ok", false).put("error", e.message ?: "No se pudo iniciar sesión con Google")\n                callback("window.NativeBridgeCallbacks.onGoogleSignIn", obj.toString())\n            }\n        }\n''')
    needle = '''        @JavascriptInterface\n        fun appVersion(): String = BuildConfig.VERSION_NAME\n'''
    insert = '''\n        @JavascriptInterface\n        fun startGoogleSignIn() {\n            runOnUiThread {\n                try {\n                    startActivityForResult(googleSignInClient.signInIntent, GOOGLE_SIGN_IN_REQUEST)\n                } catch (e: Exception) {\n                    val obj = JSONObject().put("ok", false).put("error", e.message ?: "No se pudo abrir Google Sign-In")\n                    callback("window.NativeBridgeCallbacks.onGoogleSignIn", obj.toString())\n                }\n            }\n        }\n\n        private fun normalizeEmail(email: String): String = email.trim().lowercase(Locale.ROOT)\n\n        private fun passwordHash(email: String, password: String): String {\n            val digest = MessageDigest.getInstance("SHA-256")\n            val bytes = digest.digest((normalizeEmail(email) + "|MultiAI|" + password).toByteArray(StandardCharsets.UTF_8))\n            return bytes.joinToString("") { "%02x".format(it) }\n        }\n\n        @JavascriptInterface\n        fun registerLocalAccount(name: String, email: String, password: String): String {\n            val normalized = normalizeEmail(email)\n            require(name.trim().isNotBlank()) { "Escribe tu nombre." }\n            require(normalized.contains("@")) { "Correo no válido." }\n            require(password.length >= 6) { "La contraseña debe tener al menos 6 caracteres." }\n            val slot = "localAccount:$normalized"\n            require(secureStore.get(slot).isBlank()) { "Ya existe una cuenta con ese correo en este dispositivo." }\n            val obj = JSONObject()\n                .put("id", "local-" + UUID.randomUUID().toString())\n                .put("mode", "local")\n                .put("name", name.trim())\n                .put("email", normalized)\n                .put("plan", "free")\n                .put("passwordHash", passwordHash(normalized, password))\n            secureStore.put(slot, obj.toString())\n            obj.remove("passwordHash")\n            return obj.toString()\n        }\n\n        @JavascriptInterface\n        fun loginLocalAccount(email: String, password: String): String {\n            val normalized = normalizeEmail(email)\n            val raw = secureStore.get("localAccount:$normalized")\n            require(raw.isNotBlank()) { "No existe una cuenta con ese correo en este dispositivo." }\n            val obj = JSONObject(raw)\n            require(obj.optString("passwordHash") == passwordHash(normalized, password)) { "Contraseña incorrecta." }\n            obj.remove("passwordHash")\n            return obj.toString()\n        }\n\n'''
    s = s.replace(needle, needle + insert)
kt.write_text(s)

html = root / 'app/src/main/assets/index.html'
s = html.read_text()
s = s.replace(" onVoiceResult:t=>{if(t){$('#prompt').value=($('#prompt').value+' '+t).trim();autoGrow()}},\n onError:e=>toast(e,true)", " onVoiceResult:t=>{if(t){$('#prompt').value=($('#prompt').value+' '+t).trim();autoGrow()}},\n onGoogleSignIn:r=>{handleGoogleSignInResult(r)},\n onError:e=>toast(e,true)")
old = "async function submitAccount(){const backend=getBackendUrl(),email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();if(!backend)return $('#authError').textContent='Primero configura la URL del servidor MultiAI en Ajustes > Seguridad. Puedes entrar como invitado mientras tanto.';if(!email||!password||(authMode==='register'&&!name))return $('#authError').textContent='Completa los campos.';const btn=$('#authSubmitBtn');btn.disabled=true;try{const path=authMode==='register'?'auth/register':'auth/login';const r=await nativeRequest(joinUrl(backend,path),'POST',{name,email,password},'','none');if(!r.ok)throw new Error(extractApiError(r));const d=JSON.parse(r.body||'{}');setAccount(d.user,d.token);hideAuthForm();toast(d.user?.plan==='plus'?'¡Founder PLUS de por vida activado!':'Sesión iniciada')}catch(e){$('#authError').textContent=e.message}finally{btn.disabled=false}}"
new = "async function submitAccount(){const backend=getBackendUrl(),email=$('#authEmail').value.trim(),password=$('#authPassword').value,name=$('#authName').value.trim();if(!email||!password||(authMode==='register'&&!name))return $('#authError').textContent='Completa los campos.';const btn=$('#authSubmitBtn');btn.disabled=true;$('#authError').textContent='';try{if(backend){const path=authMode==='register'?'auth/register':'auth/login';const r=await nativeRequest(joinUrl(backend,path),'POST',{name,email,password},'','none');if(!r.ok)throw new Error(extractApiError(r));const d=JSON.parse(r.body||'{}');setAccount(d.user,d.token);hideAuthForm();toast(d.user?.plan==='plus'?'¡Founder PLUS de por vida activado!':'Sesión iniciada');return}if(!isAndroid)throw new Error('La cuenta local funciona dentro de la app Android.');let raw;if(authMode==='register')raw=Android.registerLocalAccount(name,email,password);else raw=Android.loginLocalAccount(email,password);const user=JSON.parse(raw);setAccount(user,'local');hideAuthForm();toast(authMode==='register'?'Cuenta creada en este dispositivo':'Sesión iniciada')}catch(e){$('#authError').textContent=e.message||String(e)}finally{btn.disabled=false}}"
s = s.replace(old, new)
old = "function startGoogle(){const client=localStorage.getItem('multiai_google_client')||'';if(!client){$('#authError').textContent='Google Sign-In está preparado, pero falta configurar el Google OAuth Client ID del proyecto en Ajustes > Seguridad.';return}$('#authError').textContent='Google Sign-In nativo se activará al conectar las credenciales OAuth de Android. No se usa Puter.'}"
new = "function startGoogle(){if(!isAndroid||!Android.startGoogleSignIn){$('#authError').textContent='Google Sign-In solo está disponible en la app Android.';return}$('#authError').textContent='';try{Android.startGoogleSignIn()}catch(e){$('#authError').textContent=e.message||String(e)}}\nfunction handleGoogleSignInResult(r){if(!r?.ok){$('#authError').textContent=r?.error||'No se pudo iniciar sesión con Google.';return}if(!r.email){$('#authError').textContent='Google no devolvió un correo para esta cuenta.';return}const user={id:'google-'+(r.id||r.email),mode:'google',name:r.name||'Usuario',email:r.email,photo:r.photo||'',plan:'free'};setAccount(user,'google-local');hideAuthForm();toast('Sesión iniciada con Google')}"
s = s.replace(old, new)
s = s.replace('MultiAI v0.5.0 alpha', 'MultiAI v0.5.1 alpha')
s = s.replace('Puter fue eliminado. Incluye Invitado, arquitectura de cuenta MultiAI, Founder PLUS #01–#20 y soporte de Ollama para PLUS.', 'Puter fue eliminado. Incluye Invitado, cuentas locales funcionales, Google Sign-In nativo, arquitectura Founder PLUS #01–#20 y soporte de Ollama para PLUS.')
html.write_text(s)

print('Applied MultiAI v0.5.1 patch')
